import { Injectable } from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';
import { MatIconRegistry } from '@angular/material/icon';

/**
 * SVG Mat Icon Registry 등록
 *
 * @export
 * @class RegSvgIconService
 */
@Injectable({
  providedIn: 'root',
})
export class RegSvgIconService {
  constructor(
    protected matIconRegistry: MatIconRegistry,
    protected domSanitizer: DomSanitizer
  ) {}

  init(): void {
    this.matIconRegistry.addSvgIcon(
      'instagram',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/instagram.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'facebook',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/facebook.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'login',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/login.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'logout',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/logout.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'arrowBack',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/arrow_back.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'arrowForward',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/arrow_forward.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'mail',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/mail.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'email',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/email.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'phone',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/phone.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'mphone',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/mphone.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'kakao',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/kakao.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'instagram_contact',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/instagram_contact.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'diving',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/diving.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'diving_home',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/diving_home.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'single',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/single.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'scuba',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/scuba.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'dive_computer',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/dive_computer.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'light',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/light.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'many_dive',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/many_dive.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'padi',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/padi.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'rescue',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/rescue.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'efr',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/efr.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'dive_master',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/dive_master.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'nitrox',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/nitrox.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'special_dive',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/special_dive.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'scuba_reminder',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/scuba_reminder.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'home',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/home.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'home_ico',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/home_ico.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'single_home',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/single_home.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'single_edu',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/single_edu.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'edu_fun',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/edu_fun.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'peso',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/peso.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'dollar',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/dollar.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'pickup_car_small',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/pickup_car_small.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'pickup_car_big',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/pickup_car_big.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'arrow_roundtrip',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/arrow_roundtrip.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'arrow_right',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/arrow_right.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'arrow_left',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/arrow_left.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'oceanjet',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/oceanjet.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'tour01',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/tour01.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'tour02',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/tour02.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'firefly',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/firefly.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'search',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/search.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'search_up',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/search_up.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'search_down',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/search_down.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'search_reset',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/search_reset.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'time',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/time.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'eye',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/eye.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'comment',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/comment.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'list',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/list.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'download',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/download.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'reply_bullet',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/reply_bullet.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'edit',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/edit.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'delete',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/delete.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'cancel',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/cancel.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'editor_add',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/editor_add.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'editor_active',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/editor_active.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'upload',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/upload.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'images',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/images.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'user_check',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/user_check.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'user',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/user.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'password',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/password.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'menu_mobile',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/menu_mobile.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'info',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/info.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'dollarSign',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/dollarSign.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'image',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/image.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'messageCircle',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/messageCircle.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'edit3',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        '/assets/images/icon/edit3.svg'
      )
    );
  }
}
